name: wads-final-project

services:
  app:
    image: ${DOCKER_USERNAME}/wads-final-project:latest

    build:
      context: .
      dockerfile: Dockerfile

    container_name: wads-final-project-container

    env_file:
      - .env.production

    ports:
      - "3028:3000"

    restart: unless-stopped