name: Check Running App

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: self-hosted

    steps:
      - name: Wait for application
        run: sleep 15

      - name: Check container
        run: |
          docker ps -a
          docker inspect \
            --format='Status={{.State.Status}} ExitCode={{.State.ExitCode}} Restarting={{.State.Restarting}}' \
            wads-final-project-container

      - name: Show logs
        run: docker logs --tail=200 wads-final-project-container

      - name: Test local website
        run: |
          curl -v --max-time 20 http://127.0.0.1:3028/